// Code generated by goyacc -o grammar.go grammar.y. DO NOT EDIT.

//line grammar.y:1

package pattern

import __yyfmt__ "fmt"

//line grammar.y:3

//line grammar.y:5
type yySymType struct {
	yys int
	num float64
	str string

	pattern Pattern
	arrdef  ArrayDefinition
	arrdefl []ArrayDefinition
	objdef  ObjectDefinition
	objdefl []ObjectDefinition
	opid    OptionalIdentifier
	opidl   []OptionalIdentifier
	ass     Assignment
	ref     Reference
	ind     Index
	key     Key
	bnd     Binding
}

const NULL = 57346
const TRUE = 57347
const FALSE = 57348
const NUMBER = 57349
const STRING = 57350
const IDENTIFIER = 57351

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NULL",
	"TRUE",
	"FALSE",
	"NUMBER",
	"STRING",
	"IDENTIFIER",
	"'['",
	"']'",
	"','",
	"':'",
	"'?'",
	"'{'",
	"'}'",
	"'<'",
	"'='",
	"'>'",
	"'.'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 65

var yyAct = [...]int8{
	44, 25, 27, 29, 32, 33, 31, 30, 52, 4,
	13, 49, 50, 45, 5, 8, 28, 29, 32, 33,
	31, 30, 42, 4, 38, 51, 15, 21, 5, 40,
	41, 20, 37, 24, 11, 4, 22, 23, 46, 39,
	5, 47, 18, 19, 36, 16, 17, 45, 10, 48,
	15, 53, 6, 10, 35, 1, 43, 34, 26, 14,
	9, 12, 7, 3, 2,
}

var yyPact = [...]int16{
	25, -1000, -1000, -1000, 41, 18, -1000, 34, -1000, 29,
	-1000, -1000, 15, -1000, 23, -1000, -1000, 46, -1, 31,
	-1000, 42, -1, 26, -1000, -1000, 13, -1000, 4, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1, -1000, -1000, -1,
	-1000, 38, 40, -8, -1000, 11, -1000, -1000, -11, -1000,
	38, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 64, 63, 54, 1, 2, 15, 62, 10, 61,
	60, 59, 58, 57, 0, 56,
}

var yyR1 = [...]int8{
	0, 3, 3, 1, 1, 7, 7, 6, 6, 2,
	2, 9, 9, 8, 8, 10, 11, 4, 4, 4,
	5, 5, 5, 5, 5, 5, 5, 12, 13, 15,
	15, 14, 14,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 3, 1, 3, 3, 4, 2,
	3, 1, 3, 3, 4, 1, 1, 1, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 4, 3, 1,
	3, 1, 2,
}

var yyChk = [...]int16{
	-1000, -3, -1, -2, 10, 15, 11, -7, -6, -10,
	7, 16, -9, -8, -11, 8, 11, 12, 13, 14,
	16, 12, 13, 14, -6, -4, -12, -5, 17, 4,
	8, 7, 5, 6, -13, -3, 13, -8, -4, 13,
	-5, 17, 18, -15, -14, 9, -4, -4, 9, 19,
	20, 14, 19, -14,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 0, 0, 3, 0, 5, 0,
	15, 9, 0, 11, 0, 16, 4, 0, 0, 0,
	10, 0, 0, 0, 6, 7, 17, 18, 0, 20,
	21, 22, 23, 24, 25, 26, 0, 12, 13, 0,
	19, 0, 0, 0, 29, 31, 8, 14, 0, 28,
	0, 32, 27, 30,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 12, 3, 20, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 13, 3,
	17, 18, 19, 14, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 10, 3, 11, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 15, 3, 16,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = true
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:46
		{
			yylex.(*lex).out = yyDollar[1].pattern
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:47
		{
			yylex.(*lex).out = yyDollar[1].pattern
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:50
		{
			yyVAL.pattern = Array{}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:51
		{
			yyVAL.pattern = Array{yyDollar[2].arrdefl}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:54
		{
			yyVAL.arrdefl = []ArrayDefinition{yyDollar[1].arrdef}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:55
		{
			yyVAL.arrdefl = append(yyDollar[1].arrdefl, yyDollar[3].arrdef)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:58
		{
			yyVAL.arrdef = ArrayDefinition{Index: yyDollar[1].ind, Optional: false, Assignment: yyDollar[3].ass}
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:59
		{
			yyVAL.arrdef = ArrayDefinition{Index: yyDollar[1].ind, Optional: true, Assignment: yyDollar[4].ass}
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:62
		{
			yyVAL.pattern = Object{}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:63
		{
			yyVAL.pattern = Object{yyDollar[2].objdefl}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:66
		{
			yyVAL.objdefl = []ObjectDefinition{yyDollar[1].objdef}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:67
		{
			yyVAL.objdefl = append(yyDollar[1].objdefl, yyDollar[3].objdef)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:70
		{
			yyVAL.objdef = ObjectDefinition{Key: yyDollar[1].key, Optional: false, Assignment: yyDollar[3].ass}
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:71
		{
			yyVAL.objdef = ObjectDefinition{Key: yyDollar[1].key, Optional: true, Assignment: yyDollar[4].ass}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:74
		{
			yyVAL.ind = Number(yyDollar[1].num)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:78
		{
			yyVAL.key = String(yyDollar[1].str)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:82
		{
			yyVAL.ass = yyDollar[1].bnd
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:83
		{
			yyVAL.ass = yyDollar[1].ass
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:84
		{
			yyVAL.ass = BoundLiteral{yyDollar[1].bnd, Assignment(yyDollar[2].ass)}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:87
		{
			yyVAL.ass = Null{}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:88
		{
			yyVAL.ass = String(yyDollar[1].str)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:89
		{
			yyVAL.ass = Number(yyDollar[1].num)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:90
		{
			yyVAL.ass = Boolean(true)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:91
		{
			yyVAL.ass = Boolean(false)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:93
		{
			yyVAL.ass = yyDollar[1].ref
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:94
		{
			yyVAL.ass = yyDollar[1].pattern
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:97
		{
			yyVAL.bnd = Binding(yyDollar[3].str)
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:100
		{
			yyVAL.ref = Reference(yyDollar[2].opidl)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:103
		{
			yyVAL.opidl = []OptionalIdentifier{yyDollar[1].opid}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:104
		{
			yyVAL.opidl = append(yyDollar[1].opidl, yyDollar[3].opid)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:108
		{
			yyVAL.opid = OptionalIdentifier{Identifier: Identifier(yyDollar[1].str), Optional: false}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:109
		{
			yyVAL.opid = OptionalIdentifier{Identifier: Identifier(yyDollar[1].str), Optional: true}
		}
	}
	goto yystack /* stack new state and value */
}
